### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by mediaminister** [retrospect-addon/kodi.emulator.ascii#22]
### Describe the bug

`keyboard.get_next_input()` fails with an IndexError when you do a search with an empty search string

## Expected Behavior

`keyboard.get_next_input()` should return `None`

## Actual Behavior

`keyboard.get_next_input()` fails with an IndexError

### To Reproduce

You can find the failing unit test here, search for IndexError:
https://github.com/mediaminister/plugin.video.vtm.go/runs/1284985655?check_suite_focus=true

### Stack Trace

```
2020-10-21T05:40:54.9836179Z ======================================================================
2020-10-21T05:40:54.9836678Z ERROR: test_search_menu (tests.test_routing.TestRouting)
2020-10-21T05:40:54.9837348Z ----------------------------------------------------------------------
2020-10-21T05:40:54.9837700Z Traceback (most recent call last):
2020-10-21T05:40:54.9839661Z   File "/home/runner/work/plugin.video.vtm.go/plugin.video.vtm.go/tests/test_routing.py", line 76, in test_search_menu
2020-10-21T05:40:54.9840766Z     addon.run([routing.url_for(addon.show_search), '0', ''])
2020-10-21T05:40:54.9841667Z   File "/home/runner/work/plugin.video.vtm.go/plugin.video.vtm.go/resources/lib/addon.py", line 217, in run
2020-10-21T05:40:54.9842390Z     routing.run(params)
2020-10-21T05:40:54.9843276Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/routing.py", line 130, in run
2020-10-21T05:40:54.9843922Z     self._dispatch(self.path)
2020-10-21T05:40:54.9844836Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/routing.py", line 141, in _dispatch
2020-10-21T05:40:54.9845470Z     view_func(**kwargs)
2020-10-21T05:40:54.9846216Z   File "/home/runner/work/plugin.video.vtm.go/plugin.video.vtm.go/resources/lib/addon.py", line 163, in show_search
2020-10-21T05:40:54.9846944Z     Search().show_search(query)
2020-10-21T05:40:54.9847754Z   File "/home/runner/work/plugin.video.vtm.go/plugin.video.vtm.go/resources/lib/modules/search.py", line 35, in show_search
2020-10-21T05:40:54.9848755Z     query = kodiutils.get_search_string(heading=kodiutils.localize(30009))  # Search VTM GO
2020-10-21T05:40:54.9849800Z   File "/home/runner/work/plugin.video.vtm.go/plugin.video.vtm.go/resources/lib/kodiutils.py", line 228, in get_search_string
2020-10-21T05:40:54.9850652Z     keyboard.doModal()
2020-10-21T05:40:54.9851444Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/xbmc.py", line 118, in doModal
2020-10-21T05:40:54.9852042Z     self.__input = keyboard.get_next_input()
2020-10-21T05:40:54.9852882Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/sakee/stub.py", line 24, in get_next_input
2020-10-21T05:40:54.9853458Z     return self.__queue.pop(0)
2020-10-21T05:40:54.9853809Z IndexError: pop from empty list
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- SAKE buid: 0.0.8

**Comment by basrieter** [comment]
Indeed, let me fix that.
